name: 'Download file from Backblaze B2'
description: 'Download file from Backblaze B2'
author: 'sksat <sksat@sksat.net>'

inputs:
  key_id:
    description: key ID
    required: true
  key:
    description: key (listBuckets capability required)
    required: true
  bucket:
    description: bucket
    required: true
  file_name:
    description: source file or directory
    required: true
  file_id:
    description: file id (not implemented)
  local_name:
    description: local file name
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.key_id }}
    - ${{ inputs.key }}
    - ${{ inputs.bucket }}
    - ${{ inputs.file_name }}
    - ${{ inputs.local_name }}
